#!usr/bin/python
import  random
import time
import math
import calendar
print("hello,word")
'''这个是第一个注释'''
a=50
b=50000000000000
print(id(a),id(b))
ran=random.randrange(0,101,1)
print(ran)
cen=["我","喜","欢","你"]
random.shuffle(cen)
print(cen)
print(random.randint(0,1000))
print("大家好，我叫%s,今年%d 岁"%('余豪',11))
t1="{1} {1} {0}".format("yuhao","good")
print(t1)
if a==50:
   print("true")
else:
    print("false")
for i,num in enumerate(cen): print(i,num)
for i in range(10):
   print(i,random.choice(range(20,200)))
print("sixe:",len(cen[1:3]))
print(cen)
cen.reverse()
print(cen)
local=time.localtime(time.time())
print(local)
f=open("yuhao.txt","w+")
sum=0
a=time.time()
for i in range(2,100000):
    j=1
    count=0
    while(j<i):
        if (i%j==0):
            count+=1
        j+=1
    if count==1:
       f.write(str(i))
       f.write("\t")
       sum+=1
       if sum%10==0:
          f.write("\n")
b=time.time()
print("total:", sum, "time:", b-a)
f.write("\n个数：%d,总用时%.2fs" %(sum, b-a))
f.close()
cal=calendar.month(2018,1)
print(cal)

str=input("please input:")
print("data is:",str)

'''关于数据的个格式化问题'''

