#!/usr/bin/python3


def hello(str3):
    print("你好"+str3, 2-9)


def findSmallestInt(arr):
    return min(arr)


def remove_smallest(numbers):
 ##  raise NotImplementedError("TODO: remove_smallest")
   if(len(numbers)!=0):
         i= numbers.index(min(numbers))
         numbers.remove(numbers[i])


def nb_year(p0, percent, aug, p):
    sum = p0
    count = 0
    while(sum< p ):
        sum=sum*(1+percent*1.0/100)+aug
        count+=1
    return  count






